apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: webapp-namespace
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name:  myapp-secret-docker
      containers:
      - name: my-go-app
        image: csye712504/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DB_HOST
          value: database-service.webapp-namespace.svc.cluster.local
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_NAME
      initContainers:
      - name: flyway-init-container
        image: csye712504/flyway:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: database-service.webapp-namespace.svc.cluster.local
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_NAME
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_SCHEMA


