apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: myapp

---
#  Head less service for database pods(StateFull sets)
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: webapp-namespace
spec:
  selector:
    app: database
  clusterIP: None # Headless service
  ports:
  - port: 3306
    targetPort: 3306