apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: gcp-storage
# provisioner: pd.csi.storage.gke.io
# parameters:
#   type: pd-standard
#   fsType: ext4
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true
# ---